subjectsData = {
    Groups:[
        {
            type: "torzs",
            name: "torzsanyag",
            fullname: "Törzstárgyak",
            subjects:[
                {
                    name: "Geodézia I.",
                    code: "BMEEOAFAT41",
                    credit: 3,
                    lecture: 1,
                    seminar: 2,
                    lab: 0,
                    consultation: 0,
                    day: 0,
                    requirement: "Félévközi",
                    felev: 1,
                    elo:[]
                },                
                {
                    name: "Építőmérnöki Kémia",
                    code: "BMEEOEMAT41",
                    credit: 2,
                    lecture: 2,
                    seminar: 0,
                    lab: 0,
                    consultation: 0,
                    requirement: "Félévközi",
                    felev: 1,
                    elo:[]
                },
                {
                    name: "Építőmérnöki ábrázolás",
                    code: "BMEEOEMAT42",
                    credit: 4,
                    lecture: 2,
                    seminar: 2,
                    lab: 0,
                    consultation: 0,
                    requirement: "Félévközi",
                    felev: 1,
                    elo:[]
                },
                {
                    name: "Építőmérnöki CAD",
                    code: "BMEEOFTAT41",
                    credit: 2,
                    lecture: 0,
                    seminar: 2,
                    lab: 0,
                    consultation: 0,
                    requirement: "Félévközi",
                    felev: 1,
                    elo:[]
                },
                {
                    name: "Geológia",
                    code: "BMEEOGMAT41",
                    credit: 3,
                    lecture: 1,
                    seminar: 2,
                    lab: 0,
                    consultation: 0,
                    requirement: "Vizsga",
                    felev: 1,
                    elo:[]
                },
                {
                    name: "A statika és dinamika alapjai",
                    code: "BMEEOTMAT41",
                    credit: 6,
                    lecture: 0,
                    seminar: 5,
                    lab: 0,
                    consultation: 0,
                    requirement: "Vizsga",
                    felev: 1,
                    elo:[]
                },
                {
                    name: "Matematika A1a",
                    code: "BMETE90AX00",
                    credit: 6,
                    lecture: 4,
                    seminar: 2,
                    lab: 0,
                    consultation: 0,
                    requirement: "Vizsga",
                    felev: 1,
                    elo:[]
                },
                {
                    name: "Építőmérnöki fizika",
                    code: "BMETE11AX13",
                    credit: 2,
                    lecture: 2,
                    seminar: 0,
                    lab: 0,
                    consultation: 0,
                    requirement: "Félévközi",
                    felev: 1,
                    elo:[]
                },    
                {
                    name: "Geodézia II.",
                    code: "BMEEOAFAT42",
                    credit: 4,
                    lecture: 2,
                    seminar: 2,
                    lab: 0,
                    consultation: 0,
                    requirement: "Vizsga",
                    felev: 2,
                    elo:["BMEEOAFAT41","BMEEOFTAT41"]
                },    
                {
                    name: "Építőanyagok I.",
                    code: "BMEEOEMAT43",
                    credit: 5,
                    lecture: 2,
                    seminar: 0,
                    lab: 2,
                    consultation: 0,
                    requirement: "Vizsga",
                    felev: 2,
                    elo:["BMEEOEMAT41"]
                },    
                {
                    name: "Építőmérnöki Informatika",
                    code: "BMEEOFTAT42",
                    credit: 5,
                    lecture: 2,
                    seminar: 2,
                    lab: 0,
                    consultation: 0,
                    requirement: "Félévközi",
                    felev: 2,
                    elo:[]
                },    
                {
                    name: "Magasépítéstan alapjai",
                    code: "BMEEOEMAT44",
                    credit: 3,
                    lecture: 1,
                    seminar: 2,
                    lab: 0,
                    consultation: 0,
                    requirement: "Félévközi",
                    felev: 2,
                    elo:["BMEEOEMAT42"]
                },    
                {
                    name: "Elemi szilárdásgtan",
                    code: "BMEEOTMAT42",
                    credit: 6,
                    lecture: 0,
                    seminar: 5,
                    lab: 0,
                    consultation: 0,
                    requirement: "Félévközi",
                    felev: 2,
                    elo:[ "BMEEOTMAT41","BMETE90AX00~"]
                },    
                {
                    name: "Hidraulika I.",
                    code: "BMEEOVVAT42",
                    credit: 3,
                    lecture: 2,
                    seminar: 1,
                    lab: 0,
                    consultation: 0,
                    requirement: "Vizsga",
                    felev: 2,
                    elo:[]
                },    
                {
                    name: "Matematika A2a",
                    code: "BMETE90AX02",
                    credit: 6,
                    lecture: 4,
                    seminar: 2,
                    lab: 0,
                    consultation: 0,
                    requirement: "Vizsga",
                    felev: 2,
                    elo:["BMETE90AX00"]
                }, 
                {
                    name: "Testnevelés BSc 1/A",
                    code: "BMEGT70BS1A",
                    credit: 0,
                    lecture: 0,
                    seminar: 2,
                    lab: 0,
                    consultation: 0,
                    requirement: "Aláírás",
                    felev: 2,
                    elo:[],
                },   
                {
                    name: "Geodézia mérőgyakorlat",
                    code: "BMEEOAFAT43",
                    credit: 3,
                    lecture: 0,
                    seminar: 0,
                    lab: 0,
                    consultation: 0,
                    requirement: "Félévközi",
                    felev: 3,
                    elo:["!BMEEOAFAT42~"]
                },    
                {
                    name: "Talajmechanika",
                    code: "BMEEOGMAT42",
                    credit: 4,
                    lecture: 2,
                    seminar: 2,
                    lab: 0,
                    consultation: 0,
                    requirement: "Félévközi",
                    felev: 3,
                    elo:[ "BMEEOGMAT41","BMEEOTMAT42"]
                },    
                {
                    name: "Térinformatika",
                    code: "BMEEOFTAT43",
                    credit: 3,
                    lecture: 2,
                    seminar: 1,
                    lab: 0,
                    consultation: 0,
                    requirement: "Félévközi",
                    felev: 3,
                    elo:[]
                },    
                {
                    name: "Tartószerkezetek méretezésének alapjai",
                    code: "BMEEOHSAT41",
                    credit: 3,
                    lecture: 2,
                    seminar: 0,
                    lab: 0,
                    consultation: 0,
                    requirement: "Félévközi",
                    felev: 3,
                    elo:["BMEEOTMAT41"]
                },    
                {
                    name: "Tartók statikája I.",
                    code: "BMEEOTMAT43",
                    credit: 4,
                    lecture: 4,
                    seminar: 0,
                    lab: 0,
                    consultation: 0,
                    requirement: "Vizsga",
                    felev: 3,
                    elo:["BMEEOTMAT42","BMETE90AX00"]
                },    
                {
                    name: "Vasúti pályák",
                    code: "BMEEOUVAT41",
                    credit: 3,
                    lecture: 3,
                    seminar: 0,
                    lab: 0,
                    consultation: 0,
                    requirement: "Vizsga",
                    felev: 3,
                    elo:[]
                },    
                {
                    name: "Környezetmérnöki alapok",
                    code: "BMEEOVKAT41",
                    credit: 3,
                    lecture: 2,
                    seminar: 0,
                    lab: 0,
                    consultation: 0,
                    requirement: "Félévközi",
                    felev: 3,
                    elo:[]
                },    
                {
                    name: "Közművek I.",
                    code: "BMEEOVKAT42",
                    credit: 3,
                    lecture: 2,
                    seminar: 1,
                    lab: 0,
                    consultation: 0,
                    requirement: "Vizsga",
                    felev: 3,
                    elo:["BMEEOVVAT42"]
                },    
                {
                    name: "Hidrológia I.",
                    code: "BMEEOVVAT41",
                    credit: 3,
                    lecture: 2,
                    seminar: 1,
                    lab: 0,
                    consultation: 0,
                    requirement: "Félévközi",
                    felev: 3,
                    elo:[]
                },    
                {
                    name: "Matematika A3 építőmérnököknek",
                    code: "BMETE90AX07",
                    credit: 4,
                    lecture: 2,
                    seminar: 2,
                    lab: 0,
                    consultation: 0,
                    requirement: "Vizsga",
                    felev: 3,
                    elo:["BMETE90AX02"]
                },
                {
                    name: "Testnevelés BSc 2/A",
                    code: "BMEGT70BS2A",
                    credit: 0,
                    lecture: 0,
                    seminar: 2,
                    lab: 0,
                    consultation: 0,
                    requirement: "Aláírás",
                    felev: 3,
                    elo:[],
                },    
                {
                    name: "Földművek",
                    code: "BMEEOGMAT43",
                    credit: 3,
                    lecture: 2,
                    seminar: 1,
                    lab: 0,
                    consultation: 0,
                    requirement: "Vizsga",
                    felev: 4,
                    elo:["BMEEOGMAT42"]
                },    
                {
                    name: "Acélszerkezetek",
                    code: "BMEEOHSAT42",
                    credit: 3,
                    lecture: 3,
                    seminar: 0,
                    lab: 0,
                    consultation: 0,
                    requirement: "Félévközi",
                    felev: 4,
                    elo:["BMEEOTMAT42","BMEEOEMAT43~","BMEEOHSAT41"]
                },    
                {
                    name: "Vasbetonszerkezetek",
                    code: "BMEEOHSAT43",
                    credit: 3,
                    lecture: 3,
                    seminar: 0,
                    lab: 0,
                    consultation: 0,
                    requirement: "Félévközi",
                    felev: 4,
                    elo:["BMEEOTMAT42","BMEEOEMAT43~","BMEEOHSAT41"]
                },    
                {
                    name: "Utak",
                    code: "BMEEOUVAT42",
                    credit: 2,
                    lecture: 2,
                    seminar: 0,
                    lab: 0,
                    consultation: 0,
                    requirement: "Félévközi",
                    felev: 4,
                    elo:["BMEEOUVAT41"]
                },    
                {
                    name: "Vízépítés, vízgazdálkodás",
                    code: "BMEEOWAT43",
                    credit: 3,
                    lecture: 2,
                    seminar: 1,
                    lab: 0,
                    consultation: 0,
                    requirement: "Vizsga",
                    felev: 4,
                    elo:["BMEEOVVAT41","BMEEOVVAT42"]
                },    
                {
                    name: "Építőmérnöki kommunikációs készs.",
                    code: "BMEGT60A6E0",
                    credit: 2,
                    lecture: 0,
                    seminar: 2,
                    lab: 0,
                    consultation: 0,
                    requirement: "Félévközi",
                    felev: 4,
                    elo:[]
                },    
                {
                    name: "Üzleti jog",
                    code: "BMEGT55A001",
                    credit: 2,
                    lecture: 2,
                    seminar: 0,
                    lab: 0,
                    consultation: 0,
                    requirement: "Félévközi",
                    felev: 4,
                    elo:[]
                },    
                {
                    name: "Alapozás",
                    code: "BMEEOGMAT45",
                    credit: 4,
                    lecture: 2,
                    seminar: 1,
                    lab: 0,
                    consultation: 0,
                    requirement: "Vizsga",
                    felev: 5,
                    elo:[ "BMEEOGMAT43"]
                },    
                {
                    name: "Menedzsment és vállalkozásgazdaságtan",
                    code: "BMEGT20A001  ",
                    credit: 4,
                    lecture: 4,
                    seminar: 0,
                    lab: 0,
                    consultation: 0,
                    requirement: "Félévközi",
                    felev: 5,
                    elo:[]
                },    
                {
                    name: "Mikro- és makroökonómia",
                    code: "BMEGT30A001",
                    credit: 4,
                    lecture: 4,
                    seminar: 0,
                    lab: 0,
                    consultation: 0,
                    requirement: "Vizsga",
                    felev: 6,
                    elo:[]
                },    
                {
                    name: "Építési projektek szervezése",
                    code: "BMEEPEKAT41",
                    credit: 3,
                    lecture: 2,
                    seminar: 1,
                    lab: 0,
                    consultation: 0,
                    requirement: "Félévközi",
                    felev: 6,
                    elo:[ "BMEEOEMAT44","BMEEOGMAT42"]
                },    
                {
                    name: "Település- és régiófejlesztés",
                    code: "BMEEOUVAT43",
                    credit: 3,
                    lecture: 2,
                    seminar: 0,
                    lab: 0,
                    consultation: 0,
                    requirement: "Félévközi",
                    felev: 7,
                    elo:[]
                },    
                {
                    name: "Szabadon választható 1",
                    code: "Szabad01",
                    credit: 2,
                    lecture: 2,
                    seminar: 0,
                    lab: 0,
                    consultation: 0,
                    requirement: "Félévközi/Vizsga",
                    felev: 7,
                    elo:[]
                },    
                {
                    name: "Szabadon választható 2",
                    code: "Szabad02",
                    credit: 2,
                    lecture: 2,
                    seminar: 0,
                    lab: 0,
                    consultation: 0,
                    requirement: "Félévközi/Vizsga",
                    felev: 7,
                    elo:[]
                },      
                {
                    name: "Szabadon választható 3",
                    code: "Szabad03",
                    credit: 2,
                    lecture: 2,
                    seminar: 0,
                    lab: 0,
                    consultation: 0,
                    requirement: "Félévközi/Vizsga",
                    felev: 7,
                    elo:[]
                },      
                {
                    name: "Szabadon választható 4",
                    code: "Szabad04",
                    credit: 2,
                    lecture: 2,
                    seminar: 0,
                    lab: 0,
                    consultation: 0,
                    requirement: "Félévközi/Vizsga",
                    felev: 8,
                    elo:[]
                },      
                {
                    name: "Szabadon választható 5",
                    code: "Szabad05",
                    credit: 2,
                    lecture: 2,
                    seminar: 0,
                    lab: 0,
                    consultation: 0,
                    requirement: "Félévközi/Vizsga",
                    felev: 8,
                    elo:[]
                },       
                {
                    name: "Szabadon választható 6",
                    code: "Szabad06",
                    credit: 2,
                    lecture: 2,
                    seminar: 0,
                    lab: 0,
                    consultation: 0,
                    requirement: "Félévközi/Vizsga",
                    felev: 8,
                    elo:[]
                },      

            ]
        },
        {
            type: "agazat",
            name: "szerkezet",
            fullname:"Szerkezet-Építőmérnöki Ágazat", 
            subjects:[
                {
                    name: "Magasépítéstan I.",
                    code: "BMEEOEMAS42",
                    credit: 3,
                    lecture: 1,
                    seminar: 2,
                    lab: 0,
                    consultation: 0,
                    requirement: "Vizga",
                    felev: 4,
                    elo:["BMEEOEMAT44"],
                    substitutes:[],
                },
                {
                    name: "Faszerkezetek",
                    code: "BMEEOHSAS44",
                    uniquecode: "BMEEOHSAS44_1",
                    credit: 3,
                    lecture: 2,
                    seminar: 0,
                    lab: 0,
                    consultation: 0,
                    requirement: "Félévközi",
                    felev: 4,
                    elo:["BMEEOTMAT42","BMEEOHSAT41"],
                    substitutes:[],
                    parentSpecializations:["magasepites","hidesmutargy"],
                },
                {
                    name: "Faszerkezetek",
                    code: "BMEEOHSAS44",
                    uniquecode: "BMEEOHSAS44_2",
                    credit: 3,
                    lecture: 2,
                    seminar: 0,
                    lab: 0,
                    consultation: 0,
                    requirement: "Félévközi",
                    felev: 4,
                    elo:["BMEEOTMAT42","BMEEOHSAT41"],
                    substitutes:[
                        {
                            name: "BIM az építőiparban",
                            code: "BMEEOFTAM41",
                        },
                        {
                            name: "Közlekedési földművek és víztelenítése",
                            code: "BMEEOGMAI41",
                        },
                        {
                            name: "Városi környezetvédelem",
                            code: "BMEEOVKAI42",
                        },
                        {
                            name: "Közlekedési létesítmények pályaszerkezetei",
                            code: "BMEEOUVAI41",
                        },
                        {
                            name: "Műholdas helymeghatározás",
                            code: "BMEEOAFAG45",
                        },
                        {
                            name: "Térinformatikai modellezés",
                            code: "BMEEOFTAG41",
                        },
                    ],
                    parentSpecializations:["geotech","epitestech","szerkezetianyagok"],
                },
                {
                    name: "Faszerkezetek",
                    code: "BMEEOHSAS44",
                    uniquecode: "BMEEOHSAS44_3",
                    credit: 3,
                    lecture: 2,
                    seminar: 0,
                    lab: 0,
                    consultation: 0,
                    requirement: "Félévközi",
                    felev: 4,
                    elo:["BMEEOTMAT42","BMEEOHSAT41"],
                    substitutes:[
                        {
                            name: "Közlekedési földművek és víztelenítése",
                            code: "BMEEOGMAI41",
                        },
                        {
                            name: "Városi környezetvédelem",
                            code: "BMEEOVKAI42",
                        },
                        {
                            name: "Közlekedési létesítmények pályaszerkezetei",
                            code: "BMEEOUVAI41",
                        },
                        {
                            name: "Műholdas helymeghatározás",
                            code: "BMEEOAFAG45",
                        },
                        {
                            name: "Térinformatikai modellezés",
                            code: "BMEEOFTAG41",
                        },
                    ],
                    parentSpecializations:["epitmenyinformacio"],
                },
                {
                    name: "Általános szilárdságtan",
                    code: "BMEEOTMAS41",
                    credit: 3,
                    lecture: 2,
                    seminar: 0,
                    lab: 0,
                    consultation: 0,
                    requirement: "Vizsga",
                    felev: 4,
                    elo:["BMEEOTMAT43"],
                    substitutes:[],
                },
                {
                    name: "Építőanyagok II.",
                    code: "BMEEOEMAS41",
                    credit: 3,
                    lecture: 1,
                    seminar: 0,
                    lab: 2,
                    consultation: 0,
                    requirement: "Vizsga",
                    felev: 5,
                    elo:["BMEEOEMAT43"],
                    substitutes:[],
                },   
                {
                    name: "Magasépítéstan II.",
                    code: "BMEEOEMAS43",
                    credit: 3,
                    lecture: 1,
                    seminar: 2,
                    lab: 0,
                    consultation: 0,
                    requirement: "Vizsga",
                    felev: 5,
                    elo:["BMEEOEMAS42"],
                    substitutes:[],
                },
                {
                    name: "Acél- és öszvérszerkezetek",
                    code: "BMEEOHSAS47",
                    credit: 4,
                    lecture: 2,
                    seminar: 1,
                    lab: 0,
                    consultation: 0,
                    requirement: "Félévközi",
                    felev: 5,
                    elo:["BMEEOHSAT42","BMEEOHSAT43"],
                    substitutes:[],
                },
                {
                    name: "Vasbeton- és falszerkezetek",
                    code: "BMEEOHSAS42",
                    credit: 4,
                    lecture: 2,
                    seminar: 1,
                    lab: 0,
                    consultation: 0,
                    requirement: "Félévközi",
                    felev: 5,
                    elo:["BMEEOHSAT43","BMEEOEMAS42"],
                    substitutes:[],
                },
                {
                    name: "Hidak és infrastruktúra szerkezetek",
                    code: "BMEEOHSAS43",
                    credit: 3,
                    lecture: 2,
                    seminar: 0,
                    lab: 0,
                    consultation: 0,
                    requirement: "Vizsga",
                    felev: 5,
                    elo:["BMEEOHSAT42","BMEEOHSAT43"],
                    substitutes:[],
                },
                {
                    name: "Szerkezet és anyagvizsgáló laborseminar",
                    code: "BMEEOHSAS46",
                    credit: 0,
                    lecture: 0,
                    seminar: 0,
                    lab: 4,
                    consultation: 0,
                    requirement: "Félévközi",
                    felev: 5,
                    elo:["BMEEOHSAT42","BMEEOHSAT43"],
                    substitutes:[],
                },
                {
                    name: "Tartók statikája II.",
                    code: "BMEEOTMAS42",
                    credit: 4,
                    lecture: 3,
                    seminar: 1,
                    lab: 0,
                    consultation: 0,
                    requirement: "Félévközi",
                    felev: 5,
                    elo:["BMEEOTMAS41","BMETE90AX07"],
                    substitutes:[],
                },
                {
                    name: "Kőzetmechanika",
                    code: "BMEEOGMAS41",
                    uniquecode: "BMEEOGMAS41_1",
                    credit: 3,
                    lecture: 1,
                    seminar: 1,
                    lab: 0,
                    consultation: 0,
                    requirement: "Félévközi",
                    felev: 6,
                    elo:["BMEEOGMAT41"],
                    substitutes:[
                        {
                            name: "BIM az építőiparban",
                            code: "BMEEOFTAM41",
                        },
                        {
                            name: "Közlekedési földművek és víztelenítése",
                            code: "BMEEOGMAI41",
                        },
                        {
                            name: "Városi környezetvédelem",
                            code: "BMEEOVKAI42",
                        },
                        {
                            name: "Közlekedési létesítmények pályaszerkezetei",
                            code: "BMEEOUVAI41",
                        },
                        {
                            name: "Műholdas helymeghatározás",
                            code: "BMEEOAFAG45",
                        },
                        {
                            name: "Térinformatikai modellezés",
                            code: "BMEEOFTAG41",
                        },
                    ],
                    parentSpecializations:["magasepites","hidesmutargy","epitestech","szerkezetianyagok"],

                },
                {
                    name: "Kőzetmechanika",
                    code: "BMEEOGMAS41",
                    uniquecode: "BMEEOGMAS41_2",
                    credit: 3,
                    lecture: 1,
                    seminar: 1,
                    lab: 0,
                    consultation: 0,
                    requirement: "Félévközi",
                    felev: 6,
                    elo:["BMEEOGMAT41"],
                    substitutes:[],
                    parentSpecializations:["geotech"],

                },
                {
                    name: "Kőzetmechanika",
                    code: "BMEEOGMAS41",
                    uniquecode: "BMEEOGMAS41_3",
                    credit: 3,
                    lecture: 1,
                    seminar: 1,
                    lab: 0,
                    consultation: 0,
                    requirement: "Félévközi",
                    felev: 6,
                    elo:["BMEEOGMAT41"],
                    substitutes:[
                        {
                            name: "Közlekedési földművek és víztelenítése",
                            code: "BMEEOGMAI41",
                        },
                        {
                            name: "Városi környezetvédelem",
                            code: "BMEEOVKAI42",
                        },
                        {
                            name: "Közlekedési létesítmények pályaszerkezetei",
                            code: "BMEEOUVAI41",
                        },
                        {
                            name: "Műholdas helymeghatározás",
                            code: "BMEEOAFAG45",
                        },
                        {
                            name: "Térinformatikai modellezés",
                            code: "BMEEOFTAG41",
                        },
                    ],
                    parentSpecializations:["epitmenyinformacio"],

                },
                {
                    name: "BIM az építőiparban",
                    code: "BMEEOFTAM41",
                    credit: 3,
                    lecture: 2,
                    seminar: 0,
                    lab: 0,
                    consultation: 0,
                    requirement: "Félévközi",
                    felev: 5,
                    elo:[],
                    substitutes:[],
                    parentSpecializations:["epitmenyinformacio"],

                },
                {
                    name: "Földalatti műtárgyak, alapozás",
                    code: "BMEEOGMAS42",
                    credit: 3,
                    lecture: 2,
                    seminar: 1,
                    lab: 0,
                    consultation: 0,
                    requirement: "Félévközi",
                    felev: 6,
                    elo:["BMEEOGMAT45"],
                    substitutes:[],
                },
                {
                    name: "3D szerkezetkonstruálás",
                    code: "BMEEOHSAS45",
                    credit: 3,
                    lecture: 0,
                    seminar: 2,
                    lab: 0,
                    consultation: 0,
                    requirement: "Félévközi",
                    felev: 6,
                    elo:["BMEEOHSAT42","BMEEOHSAT43"],
                    substitutes:[],
                },
                {
                    name: "Szerkezettervezés projektfeladat",
                    code: "BMEEODHAS41",
                    credit: 6,
                    lecture: 0,
                    seminar: 0,
                    lab: 0,
                    consultation: 2,
                    requirement: "Félévközi",
                    felev: 6,
                    elo:["BMEEOHSAS47","BMEEOHSAS42","BMEEOGMAT45"],
                    substitutes:[],
                },
                {
                    name: "Közigazgatástan, ingatlan nyilvántartás",
                    code: "BMEEOUVAT44",
                    credit: 3,
                    lecture: 2,
                    seminar: 0,
                    lab: 0,
                    consultation: 0,
                    requirement: "Félévközi",
                    felev: 7,
                    elo:[],
                    substitutes:[],
                },
                {
                    name: "Szerkezetek geodéziája mérőgyakorlat",
                    code: "-",
                    credit: 1,
                    lecture: 0,
                    seminar: 0,
                    lab: 2,
                    consultation: 0,
                    requirement: "Félévközi",
                    felev: 7,
                    elo:["BMEEOAFAT43","BMEEOEMAT44"],
                    substitutes:[],
                },
                {
                    name: "Tartók dinamikája",
                    code: "BMEEOTMAS43",
                    credit: 3,
                    lecture: 2,
                    seminar: 0,
                    lab: 0,
                    consultation: 0,
                    requirement: "Félévközi",
                    felev: 7,
                    elo:["BMEEOTMAT43","BMETE90AX02"],
                    substitutes:[],
                },
                {
                    name: "Technikusi gyakorlat",
                    code: "BMEEODHAS42",
                    credit: 0,
                    lecture: 0,
                    seminar: 0,
                    lab: 0,
                    consultation: 0,
                    requirement: "Aláírás",
                    felev: 7,
                    elo:[],
                    substitutes:[],
                },
            ],
            specializations:[
                {
                    type: "spec",
                    name: "magasepites",
                    fullname:"Magasépítési Specializáció", 
                    subjects:[
                        {
                            name: "Magasépítési acélszerkezetek",
                            code: "BMEEOHSA-A1",
                            credit: 5,
                            lecture: 3,
                            seminar: 1,
                            lab: 0,
                            consultation: 0,
                            requirement: "Vizsga",
                            felev: 6,
                            elo:["BMEEOHSAS47"],
                            substitutes:[],
                        },
                        {
                            name: "Magasépítési vasbetonszerkezetek",
                            code: "BMEEOHSA-A2",
                            credit: 5,
                            lecture: 3,
                            seminar: 1,
                            lab: 0,
                            consultation: 0,
                            requirement: "Vizsga",
                            felev: 6,
                            elo:["BMEEOHSAS42","BMEEOHSAS44"],
                            substitutes:[],
                        },
                        {
                            name: "Épületszerkezettervezés metodikája",
                            code: "BMEEOEMA-A1",
                            credit: 2,
                            lecture: 1,
                            seminar: 1,
                            lab: 0,
                            consultation: 0,
                            requirement: "Vizsga",
                            felev: 7,
                            elo:["BMEEOEMAS43"],
                            substitutes:[],
                        },
                        {
                            name: "Szerkezettechnológia",
                            code: "BMEEOHSA-K1",
                            credit: 3,
                            lecture: 1,
                            seminar: 1,
                            lab: 0,
                            consultation: 0,
                            requirement: "Félévközi",
                            felev: 7,
                            elo:["BMEEOHSAS47","BMEEOHSAS42"],
                            substitutes:[
                                {
                                    name: "Mérnöki nagylétesítmények megvalósítása",
                                    code: "BMEEPEKA-D1",
                                },
                                {
                                    name: "Szerkezetek szerelésének szervezése",
                                    code: "BMEEPEKA-D2",
                                },
                                {
                                    name: "Betontechnológia I.",
                                    code: "BMEEOEMA-K1",
                                }, 
                            ],
                        },
                        {
                            name: "Magasépítési projektfeladat",
                            code: "BMEEOHSA-AP",
                            credit: 6,
                            lecture: 0,
                            seminar: 0,
                            lab: 0,
                            consultation: 2,
                            requirement: "Félévközi",
                            felev: 7,
                            elo:["BMEEODHAS41","BMEEOHSA-A1","BMEEOHSA-A2"],
                            substitutes:[],
                        },
                        {
                            name: "Szakdolgozat előkészítő",
                            code: "BMEEODHA-AT",
                            credit: 9,
                            lecture: 0,
                            seminar: 0,
                            lab: 0,
                            consultation: 0,
                            requirement: "Félévközi",
                            felev: 8,
                            elo:["BMEEOHSA-AP"],
                            substitutes:[],
                        },
                        {
                            name: "Szakdolgozat",
                            code: "BMEEODHA-AS",
                            credit: 15,
                            lecture: 0,
                            seminar: 0,
                            lab: 0,
                            consultation: 0,
                            requirement: "Félévközi",
                            felev: 8,
                            elo:["BMEEODHA-AT!"],
                            substitutes:[],
                        },
                    ],
                },
                {
                    type: "spec",
                    name: "hidesmutargy",
                    fullname:"Híd és Műtárgy Specializáció", 
                    subjects:[
                        {
                            name: "Acélhidak",
                            code: "BMEEOHSA-B1",
                            credit: 5,
                            lecture: 3,
                            seminar: 1,
                            lab: 0,
                            consultation: 0,
                            requirement: "Vizsga",
                            felev: 6,
                            elo:["BMEEOHSAS47","BMEEOHSAS43"],
                            substitutes:[],
                        },
                        {
                            name: "Vasbeton hidak",
                            code: "BMEEOHSA-B2",
                            credit: 4,
                            lecture: 2,
                            seminar: 1,
                            lab: 0,
                            consultation: 0,
                            requirement: "Vizsga",
                            felev: 6,
                            elo:["BMEEOHSAS42","BMEEOHSAS43","BMEEOHSAS44"],
                            substitutes:[],
                        },
                        {
                            name: "Mélyépítési műtárgyak",
                            code: "BMEEOHSA-B3",
                            credit: 3,
                            lecture: 2,
                            seminar: 0,
                            lab: 0,
                            consultation: 0,
                            requirement: "Vizsga",
                            felev: 7,
                            elo:["BMEEOHSAT43","BMEEOHSAS43","BMEEOGMAS42"],
                            substitutes:[],
                        },
                        {
                            name: "Szerkezettechnológia",
                            code: "BMEEOHSA-K1",
                            credit: 3,
                            lecture: 1,
                            seminar: 1,
                            lab: 0,
                            consultation: 0,
                            requirement: "Félévközi",
                            felev: 7,
                            elo:["BMEEOHSAS47","BMEEOHSAS42"],
                            substitutes:[
                                {
                                    name: "Mérnöki nagylétesítmények megvalósítása",
                                    code: "BMEEPEKA-D1",
                                },
                                {
                                    name: "Szerkezetek szerelésének szervezése",
                                    code: "BMEEPEKA-D2",
                                },
                                {
                                    name: "Betontechnológia I.",
                                    code: "BMEEOEMA-K1",
                                }, 
                            ],
                        },
                        {
                            name: "Hídépítési projektfeladat",
                            code: "BMEEOHSA-BP",
                            credit: 6,
                            lecture: 0,
                            seminar: 0,
                            lab: 0,
                            consultation: 2,
                            requirement: "Félévközi",
                            felev: 7,
                            elo:["BMEEODHAS41","BMEEOHSA-B1","BMEEOHSA-B2"],
                            substitutes:[],
                        },
                        {
                            name: "Szakdolgozat előkészítő",
                            code: "BMEEODHA-BT",
                            credit: 9,
                            lecture: 0,
                            seminar: 0,
                            lab: 0,
                            consultation: 0,
                            requirement: "Félévközi",
                            felev: 8,
                            elo:["BMEEOHSA-BP"],
                            substitutes:[],
                        },
                        {
                            name: "Szakdolgozat",
                            code: "BMEEODHA-BS",
                            credit: 15,
                            lecture: 0,
                            seminar: 0,
                            lab: 0,
                            consultation: 0,
                            requirement: "Félévközi",
                            felev: 8,
                            elo:["BMEEODHA-BT!"],
                            substitutes:[],
                        },
                    ],
                },
                {
                    type: "spec",
                    name: "geotech",
                    fullname:"Geotechnika Specializáció", 
                    subjects:[
                        {
                            name: "Geotechnika",
                            code: "BMEEOGMA-C1",
                            credit: 7,
                            lecture: 3,
                            seminar: 1,
                            lab: 0,
                            consultation: 0,
                            requirement: "Vizsga",
                            felev: 6,
                            elo:["BMEEOGMAT45"],
                            substitutes:[],
                        },
                        {
                            name: "Betontechnológia I.",
                            code: "BMEEOEMA-K1",
                            credit: 3,
                            lecture: 2,
                            seminar: 0,
                            lab: 0,
                            consultation: 0,
                            requirement: "Vizsga",
                            felev: 6,
                            elo:["BMEEOEMAT43"],
                            substitutes:[
                                {
                                    name: "Mérnöki nagylétesítmények megvalósítása",
                                    code: "BMEEPEKA-D1",
                                },
                                {
                                    name: "Szerkezetek szerelésének szervezése",
                                    code: "BMEEPEKA-D2",
                                },
                            ],
                        },
                        {
                            name: "Mérnökgeológia",
                            code: "BMEEOGMA-C2",
                            credit: 2,
                            lecture: 1,
                            seminar: 1,
                            lab: 0,
                            consultation: 0,
                            requirement: "Vizsga",
                            felev: 7,
                            elo:["BMEEOGMAS41"],
                            substitutes:[],
                        },
                        {
                            name: "Mélyépítési műtárgyak",
                            code: "BMEEOHSA-B3",
                            credit: 3,
                            lecture: 2,
                            seminar: 0,
                            lab: 0,
                            consultation: 0,
                            requirement: "Vizsga",
                            felev: 7,
                            elo:["BMEEOHSAT43","BMEEOHSAS43","BMEEOGMAS42"],
                            substitutes:[],
                        },
                        {
                            name: "Mélyépítési projektfeladat",
                            code: "BMEEOGMA-CP",
                            credit: 6,
                            lecture: 0,
                            seminar: 0,
                            lab: 0,
                            consultation: 2,
                            requirement: "Félévközi",
                            felev: 7,
                            elo:["BMEEODHAS41","BMEEOGMA-C1"],
                            substitutes:[],
                        },
                        {
                            name: "Szakdolgozat előkészítő",
                            code: "BMEEODHA-CT",
                            credit: 9,
                            lecture: 0,
                            seminar: 0,
                            lab: 0,
                            consultation: 0,
                            requirement: "Félévközi",
                            felev: 8,
                            elo:["BMEEOHSA-CP"],
                            substitutes:[],
                        },
                        {
                            name: "Szakdolgozat",
                            code: "BMEEODHA-CS",
                            credit: 15,
                            lecture: 0,
                            seminar: 0,
                            lab: 0,
                            consultation: 0,
                            requirement: "Félévközi",
                            felev: 8,
                            elo:["BMEEODHA-CT!"],
                            substitutes:[],
                        },
                    ],
                },
                {
                    type: "spec",
                    name: "epitestech",
                    fullname:"Építéstechnológia és Menedzsment Specializáció", 
                    subjects:[
                        {
                            name: "Építéstechnológia I.",
                            code: "BMEEOEMA-D1",
                            credit: 2,
                            lecture: 2,
                            seminar: 0,
                            lab: 0,
                            consultation: 0,
                            requirement: "Vizsga",
                            felev: 6,
                            elo:["BMEEOEMAS43"],
                            substitutes:[],
                        },
                        {
                            name: "Többdimenziós projektelemzés",
                            code: "BMEEOEMA-D3",
                            credit: 4,
                            lecture: 2,
                            seminar: 1,
                            lab: 0,
                            consultation: 0,
                            requirement: "Félévközi",
                            felev: 6,
                            elo:["BMEEOEMAS43","BMEEPEKAT41!"],
                            substitutes:[],
                        },
                        {
                            name: "Építéstechnológia II.",
                            code: "BMEEOEMA-D2",
                            credit: 3,
                            lecture: 1,
                            seminar: 1,
                            lab: 0,
                            consultation: 0,
                            requirement: "Vizsga",
                            felev: 7,
                            elo:["BMEEOEMA-D1"],
                            substitutes:[],
                        },
                        {
                            name: "Mérnöki nagylétesítmények megvalósítása",
                            code: "BMEEPEKA-D1",
                            credit: 3,
                            lecture: 2,
                            seminar: 0,
                            lab: 0,
                            consultation: 0,
                            requirement: "Vizsga",
                            felev: 7,
                            elo:["BMEEPEKAT41"],
                            substitutes:[],
                        },
                        {
                            name: "Szerkezetek szerelésének szervezése",
                            code: "BMEEPEKA-D2",
                            credit: 3,
                            lecture: 2,
                            seminar: 0,
                            lab: 0,
                            consultation: 0,
                            requirement: "Vizsga",
                            felev: 7,
                            elo:["BMEEPEKAT41"],
                            substitutes:[],
                        },
                        {
                            name: "Magasépítési projektfeladat",
                            code: "BMEEOEMA-DP",
                            credit: 6,
                            lecture: 0,
                            seminar: 0,
                            lab: 0,
                            consultation: 2,
                            requirement: "Félévközi",
                            felev: 7,
                            elo:["BMEEODHAS41","BMEEOEMA-D1","BMEEOEMA-D3"],
                            substitutes:[],
                        },
                        {
                            name: "Szakdolgozat előkészítő",
                            code: "BMEEODHA-DT",
                            credit: 9,
                            lecture: 0,
                            seminar: 0,
                            lab: 0,
                            consultation: 0,
                            requirement: "Félévközi",
                            felev: 8,
                            elo:["BMEEOEMA-DP"],
                            substitutes:[],
                        },
                        {
                            name: "Szakdolgozat",
                            code: "BMEEODHA-DS",
                            credit: 15,
                            lecture: 0,
                            seminar: 0,
                            lab: 0,
                            consultation: 0,
                            requirement: "Félévközi",
                            felev: 8,
                            elo:["BMEEODHA-DT!"],
                            substitutes:[],
                        },
                    ],
                },
                {
                    type: "spec",
                    name: "szerkezetianyagok",
                    fullname:"Szerkezeti Anyagok és Technológiák Specializáció", 
                    subjects:[
                        {
                            name: "Betontechnológia I.",
                            code: "BMEEOEMA-K1",
                            credit: 3,
                            lecture: 2,
                            seminar: 0,
                            lab: 0,
                            consultation: 0,
                            requirement: "Vizsga",
                            felev: 6,
                            elo:["BMEEOEMAT43"],
                            substitutes:[ ],
                        },
                        {
                            name: "Újrahasznosítás az építőiparban",
                            code: "BMEEOEMA-K3",
                            credit: 3,
                            lecture: 2,
                            seminar: 0,
                            lab: 0,
                            consultation: 0,
                            requirement: "Félévközi",
                            felev: 6,
                            elo:["BMEEOEMAT43"],
                            substitutes:[],
                        },
                        {
                            name: "Betontechnológia II.",
                            code: "BMEEOEMA-K2",
                            credit: 3,
                            lecture: 2,
                            seminar: 0,
                            lab: 0,
                            consultation: 0,
                            requirement: "Vizsga",
                            felev: 7,
                            elo:["BMEEOEMA-K1"],
                            substitutes:[],
                        },
                        {
                            name: "Mélyépítési műtárgyak",
                            code: "BMEEOHSA-B3",
                            credit: 3,
                            lecture: 2,
                            seminar: 0,
                            lab: 0,
                            consultation: 0,
                            requirement: "Vizsga",
                            felev: 7,
                            elo:["BMEEOHSAT43","BMEEOHSAS43","BMEEOGMAS42"],
                            substitutes:[],
                        },
                        {
                            name: "Szerkezettechnológia",
                            code: "BMEEOHSA-K1",
                            credit: 3,
                            lecture: 1,
                            seminar: 1,
                            lab: 0,
                            consultation: 0,
                            requirement: "Félévközi",
                            felev: 7,
                            elo:["BMEEOHSAS47","BMEEOHSAS42"],
                            substitutes:[
                                {
                                    name: "Mérnöki nagylétesítmények megvalósítása",
                                    code: "BMEEPEKA-D1",
                                },
                                {
                                    name: "Szerkezetek szerelésének szervezése",
                                    code: "BMEEPEKA-D2",
                                },
                            ],
                        },
                        {
                            name: "Szerkezetépítése-technológia projektfeladat",
                            code: "BMEEOEMA-KP",
                            credit: 06,
                            lecture: 0,
                            seminar: 0,
                            lab: 0,
                            consultation: 2,
                            requirement: "Félévközi",
                            felev: 7,
                            elo:["BMEEODHAS41","BMEEOEMA-K1"],
                            substitutes:[],
                        },
                        {
                            name: "Szakdolgozat előkészítő",
                            code: "BMEEODHA-KT",
                            credit: 9,
                            lecture: 0,
                            seminar: 0,
                            lab: 0,
                            consultation: 0,
                            requirement: "Félévközi",
                            felev: 8,
                            elo:["BMEEOEMA-KP"],
                            substitutes:[],
                        },
                        {
                            name: "Szakdolgozat",
                            code: "BMEEODHA-KS",
                            credit: 15,
                            lecture: 0,
                            seminar: 0,
                            lab: 0,
                            consultation: 0,
                            requirement: "Félévközi",
                            felev: 8,
                            elo:["BMEEODHA-KT!"],
                            substitutes:[],
                        },
                    ],
                },
                {
                    type: "spec",
                    name: "epitmenyinformacio",
                    fullname:"Építmény-információs Modellezés és Menedzsment Specializáció", 
                    subjects:[
                        {
                            name: "Építmény-információs mod. és menedzsment",
                            code: "BMEEOFTA-M1",
                            credit: 3,
                            lecture: 2,
                            seminar: 0,
                            lab: 0,
                            consultation: 0,
                            requirement: "Félévközi",
                            felev: 6,
                            elo:[],
                            substitutes:[],
                        },
                        {
                            name: "Építmény-információs rendszerek",
                            code: "BMEEOFTA-M2",
                            credit: 6,
                            lecture: 0,
                            seminar: 0,
                            lab: 4,
                            consultation: 0,
                            requirement: "Félévközi",
                            felev: 6,
                            elo:["BMEEOFTA-M1!"],
                            substitutes:[],
                        },
                        {
                            name: "BIM alkalmazások és technológiák",
                            code: "BMEEOEMA-M3",
                            credit: 3,
                            lecture: 2,
                            seminar: 0,
                            lab: 0,
                            consultation: 0,
                            requirement: "Vizsga",
                            felev: 7,
                            elo:["BMEEOFTAM41!"],
                            substitutes:[],
                        },
                        {
                            name: "Szakági együttműködés BIM alapokon",
                            code: "BMEEOTMA-M4",
                            credit: 3,
                            lecture: 0,
                            seminar: 0,
                            lab: 2,
                            consultation: 0,
                            requirement: "Félévközi",
                            felev: 7,
                            elo:["BMEEOFTAM41!"],
                            substitutes:[],
                        },
                        {
                            name: "Építmény-információs mod. és menedzsment proj.",
                            code: "BMEEOEMA-MP",
                            credit: 6,
                            lecture: 0,
                            seminar: 0,
                            lab: 0,
                            consultation: 2,
                            requirement: "Félévközi",
                            felev: 7,
                            elo:["BMEEODHAS41"],
                            substitutes:[],
                        },
                        {
                            name: "Szakdolgozat előkészítő",
                            code: "BMEEODHA-MT",
                            credit: 9,
                            lecture: 0,
                            seminar: 0,
                            lab: 0,
                            consultation: 0,
                            requirement: "Félévközi",
                            felev: 8,
                            elo:["BMEEOEMA-MP"],
                            substitutes:[],
                        },
                        {
                            name: "Szakdolgozat",
                            code: "BMEEODHA-MS",
                            credit: 15,
                            lecture: 0,
                            seminar: 0,
                            lab: 0,
                            consultation: 0,
                            requirement: "Félévközi",
                            felev: 8,
                            elo:["BMEEODHA-MT!"],
                            substitutes:[],
                        },
                    ],
                },
            ]
        },        
        {
            type: "agazat",
            name: "infrastr",
            fullname:"Infrastruktúra-Építőmérnöki Ágazat", 
            subjects:[
                
            ],
            specializations:[
                {
                    type: "spec",
                    name: "kozlekedesiletesitmeny",
                    fullname:"Közlekedési Létesítmények Specializáció", 
                    subjects:[
                        
                    ],
                },
                {
                    type: "spec",
                    name: "vizimernoki",
                    fullname:"Vízmérnöki Specializáció", 
                    subjects:[
                        
                    ],
                },
                {
                    type: "spec",
                    name: "vizkikozmu",
                    fullname:"Vízi Közmű és Környezetmérnöki Specializáció", 
                    subjects:[
                        
                    ],
                },
                {
                    type: "spec",
                    name: "epitmenyinformacio",
                    fullname:"Építmény-információs modellezés és menedzsment specializáció", 
                    subjects:[
                        
                    ],
                },
                {
                    type: "spec",
                    name: "geotech",
                    fullname:"Geotechnika Specializáció", 
                    subjects:[
                        
                    ],
                },
            ]
        },   
        {
            type: "agazat",
            name: "geoinfo",
            fullname:"Geoinformatika-Építőmérnöki Ágazat", 
            subjects:[
                
            ],
            specializations:[
                {
                    type: "spec",
                    name: "geodezia",
                    fullname:"Geodézia Specializáció", 
                    subjects:[
                        
                    ],
                },
                {
                    type: "spec",
                    name: "terinfo",
                    fullname:"Térinformatikai Specializáció", 
                    subjects:[
                        
                    ],
                },
                {
                    type: "spec",
                    name: "epitmenyinformacio",
                    fullname:"Építmény-információs modellezés és menedzsment specializáció", 
                    subjects:[
                        
                    ],
                },
            ]
        },         

    ]    
}